[project]
name = "mcp-duckduckgo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search",
    "httpx>=0.28.1",
    "mcp[cli]>=1.3.0",
    "beautifulsoup4>=4.13.4",
]
